/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerimetreExploitationIndexRouteImport } from './routes/perimetre-exploitation/index'
import { Route as PdvIndexRouteImport } from './routes/pdv/index'
import { Route as ConfigurationRedevancesIndexRouteImport } from './routes/configuration-redevances/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerimetreExploitationIndexRoute =
  PerimetreExploitationIndexRouteImport.update({
    id: '/perimetre-exploitation/',
    path: '/perimetre-exploitation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PdvIndexRoute = PdvIndexRouteImport.update({
  id: '/pdv/',
  path: '/pdv/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRedevancesIndexRoute =
  ConfigurationRedevancesIndexRouteImport.update({
    id: '/configuration-redevances/',
    path: '/configuration-redevances/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/configuration-redevances/': typeof ConfigurationRedevancesIndexRoute
  '/pdv/': typeof PdvIndexRoute
  '/perimetre-exploitation/': typeof PerimetreExploitationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/configuration-redevances': typeof ConfigurationRedevancesIndexRoute
  '/pdv': typeof PdvIndexRoute
  '/perimetre-exploitation': typeof PerimetreExploitationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/configuration-redevances/': typeof ConfigurationRedevancesIndexRoute
  '/pdv/': typeof PdvIndexRoute
  '/perimetre-exploitation/': typeof PerimetreExploitationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/configuration-redevances/'
    | '/pdv/'
    | '/perimetre-exploitation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/configuration-redevances'
    | '/pdv'
    | '/perimetre-exploitation'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/configuration-redevances/'
    | '/pdv/'
    | '/perimetre-exploitation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ConfigurationRedevancesIndexRoute: typeof ConfigurationRedevancesIndexRoute
  PdvIndexRoute: typeof PdvIndexRoute
  PerimetreExploitationIndexRoute: typeof PerimetreExploitationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perimetre-exploitation/': {
      id: '/perimetre-exploitation/'
      path: '/perimetre-exploitation'
      fullPath: '/perimetre-exploitation/'
      preLoaderRoute: typeof PerimetreExploitationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv/': {
      id: '/pdv/'
      path: '/pdv'
      fullPath: '/pdv/'
      preLoaderRoute: typeof PdvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration-redevances/': {
      id: '/configuration-redevances/'
      path: '/configuration-redevances'
      fullPath: '/configuration-redevances/'
      preLoaderRoute: typeof ConfigurationRedevancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ConfigurationRedevancesIndexRoute: ConfigurationRedevancesIndexRoute,
  PdvIndexRoute: PdvIndexRoute,
  PerimetreExploitationIndexRoute: PerimetreExploitationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
